services:
  db:
    image: postgres:17
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./migrations/create.sql:/docker-entrypoint-initdb.d/create.sql
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  actors:
    build: ./actors-service
    env_file: .env
    ports:
      - "8003:8003"
    environment:
      DB_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable
    depends_on:
      - db
  api-gateway:
    build: ./api-gateway
    env_file: .env
    ports:
      - "8080:8080"
    environment:
      DB_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable
    depends_on:
      - db

  auth:
    build: ./auth-service
    env_file: .env
    ports:
      - "8001:8001"
    environment:
      DB_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable
    depends_on:
      - db

  movies:
    build: ./movies-service
    env_file: .env
    ports:
      - "8002:8002"
    environment:
      DB_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable
    depends_on:
      - db

volumes:
  pg_data: